package view;


import controller.RMIMedicineManageControl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Medicine;
public class MedicineForm extends javax.swing.JPanel {

    /**
     * Creates new form MedicineForm
     */
    RMIMedicineManageControl rmiServer = new RMIMedicineManageControl();
    public MedicineForm() {
        initComponents();
        initData();
    }
    
    private void initData(){ 
        try {
            List<Medicine> resultListMedicine = new ArrayList<Medicine>();
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String [] {
              "id", "name", "price", "use", "type"
            });
            resultListMedicine = rmiServer.SearchMedicines("");
            for(int i = 0 ; i < resultListMedicine.size(); i++) {
                model.addRow(resultListMedicine.get(i).toRows());
            }
              jTable1.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        MedicineNameLabel = new javax.swing.JLabel();
        MedicineNameTextField = new javax.swing.JTextField();
        MedicinePriceLabel = new javax.swing.JLabel();
        MedicinePriceTextField = new javax.swing.JTextField();
        MedicineUseLabel = new javax.swing.JLabel();
        MedicineShapeLabel = new javax.swing.JLabel();
        MedicineShapeComboBox = new javax.swing.JComboBox<>();
        AddMedicineBtn = new javax.swing.JButton();
        UpdateMedicineBtn = new javax.swing.JButton();
        DeleteMedicineBtn = new javax.swing.JButton();
        SearchMedicineTextField = new javax.swing.JTextField();
        SearchMedicineBtn = new javax.swing.JButton();
        MedicineUsesTextField = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "name", "price", "type", "use"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        MedicineNameLabel.setText("Tên");

        MedicineNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineNameTextFieldActionPerformed(evt);
            }
        });

        MedicinePriceLabel.setText("Giá thuốc");

        MedicinePriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicinePriceTextFieldActionPerformed(evt);
            }
        });

        MedicineUseLabel.setText("Công dụng");

        MedicineShapeLabel.setText("Dạng thuốc");

        MedicineShapeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nước", "Viên", "Bột" }));
        MedicineShapeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineShapeComboBoxActionPerformed(evt);
            }
        });

        AddMedicineBtn.setText("Thêm thuốc");
        AddMedicineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMedicineBtnActionPerformed(evt);
            }
        });

        UpdateMedicineBtn.setText("Sửa thuốc");
        UpdateMedicineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMedicineBtnActionPerformed(evt);
            }
        });

        DeleteMedicineBtn.setText("Xóa thuốc");
        DeleteMedicineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMedicineBtnActionPerformed(evt);
            }
        });

        SearchMedicineTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchMedicineTextFieldActionPerformed(evt);
            }
        });

        SearchMedicineBtn.setText("Tìm kiếm");
        SearchMedicineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchMedicineBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addComponent(SearchMedicineTextField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MedicineNameTextField)
                    .addComponent(MedicinePriceTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddMedicineBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UpdateMedicineBtn)
                        .addGap(30, 30, 30)
                        .addComponent(DeleteMedicineBtn))
                    .addComponent(MedicineUsesTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MedicineUseLabel)
                            .addComponent(MedicineNameLabel)
                            .addComponent(MedicinePriceLabel)
                            .addComponent(SearchMedicineBtn))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MedicineShapeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MedicineShapeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SearchMedicineTextField)
                    .addComponent(SearchMedicineBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MedicineNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MedicineNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MedicinePriceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MedicinePriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MedicineUseLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MedicineUsesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MedicineShapeLabel)
                            .addComponent(MedicineShapeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddMedicineBtn)
                            .addComponent(UpdateMedicineBtn)
                            .addComponent(DeleteMedicineBtn)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MedicineNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicineNameTextFieldActionPerformed

    private void MedicinePriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicinePriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicinePriceTextFieldActionPerformed

    private void AddMedicineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMedicineBtnActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            Medicine medicine = new Medicine();
            String medicineName = MedicineNameTextField.getText();
            long medicinePrice = Long.parseLong(MedicinePriceTextField.getText());
            String medicineType = (String) MedicineShapeComboBox.getSelectedItem();
            String medicineUses = MedicineUsesTextField.getText();
            medicine = rmiServer.addMedicine(medicineName, medicinePrice, medicineType, medicineUses);
            model.addRow(medicine.toRows());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_AddMedicineBtnActionPerformed

    private void UpdateMedicineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMedicineBtnActionPerformed
        try {
            Medicine medicine = new Medicine();
            int currentId = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            String medicineName = MedicineNameTextField.getText();
            long medicinePrice = Long.parseLong(MedicinePriceTextField.getText());
            String medicineType = (String) MedicineShapeComboBox.getSelectedItem();
            String medicineUses = MedicineUsesTextField.getText();
            medicine = rmiServer.updateMedicine(currentId, medicineName, medicinePrice, medicineType, medicineUses);
            jTable1.setValueAt(medicineName, jTable1.getSelectedRow(), 1);
            jTable1.setValueAt(medicinePrice, jTable1.getSelectedRow(), 2);
            jTable1.setValueAt(medicineType, jTable1.getSelectedRow(), 3);
            jTable1.setValueAt(medicineUses, jTable1.getSelectedRow(), 4);
        } catch (Exception ex) {
           ex.printStackTrace();
        }
    }//GEN-LAST:event_UpdateMedicineBtnActionPerformed

    private void SearchMedicineTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMedicineTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchMedicineTextFieldActionPerformed

    private void SearchMedicineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMedicineBtnActionPerformed
        try {
                List<Medicine> resultListMedicine = new ArrayList<Medicine>();
                DefaultTableModel model = new DefaultTableModel();
                model.setColumnIdentifiers(new String [] {
                "id", "name", "price", "use", "type"
            });
                String keyword = SearchMedicineTextField.getText();
                resultListMedicine = rmiServer.SearchMedicines(keyword);
                for(int i = 0 ; i < resultListMedicine.size(); i++) {
                    System.out.println(resultListMedicine.get(i));
                    model.addRow(resultListMedicine.get(i).toRows());
                }
                jTable1.setModel(model);
            } catch (Exception ex) {
                ex.printStackTrace();
        }
    }//GEN-LAST:event_SearchMedicineBtnActionPerformed

    private void MedicineShapeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineShapeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicineShapeComboBoxActionPerformed

    private void DeleteMedicineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMedicineBtnActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int currentId = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            boolean isDeleted = rmiServer.deleteMedicine(currentId);
            if (isDeleted) {
                model.removeRow(jTable1.getSelectedRow());
                jTable1.setModel(model);
            }
        } catch (Exception ex) {
           ex.printStackTrace();
        }
    }//GEN-LAST:event_DeleteMedicineBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMedicineBtn;
    private javax.swing.JButton DeleteMedicineBtn;
    private javax.swing.JLabel MedicineNameLabel;
    private javax.swing.JTextField MedicineNameTextField;
    private javax.swing.JLabel MedicinePriceLabel;
    private javax.swing.JTextField MedicinePriceTextField;
    private javax.swing.JComboBox<String> MedicineShapeComboBox;
    private javax.swing.JLabel MedicineShapeLabel;
    private javax.swing.JLabel MedicineUseLabel;
    private javax.swing.JTextField MedicineUsesTextField;
    private javax.swing.JButton SearchMedicineBtn;
    private javax.swing.JTextField SearchMedicineTextField;
    private javax.swing.JButton UpdateMedicineBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
